org: justinedelson
app: pd-extract-environment-from-title
service: pd-extract-environment-from-title
frameworkVersion: '3'

params:
  default:
    mapRegex: \[(\w+)]$
    mapping: stg=staging,prod=production,lt=load_test
    extractRegexes: in (\w+) (in|\[),in (\w+) from

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  environment:
    PD_API_KEY: ${param:pagerDutyAPIKey}
    MAP_REGEX: ${param:mapRegex}
    MAPPING: ${param:mapping}
    EXTRACT_REGEXES: ${param:extractRegexes}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  extractTitleRegex:
    handler: bin/extractTitleRegex
    events:
      - httpApi:
          path: /regex
          method: post
  extractAndMap:
    handler: bin/extractAndMap
    events:
      - httpApi:
          path: /map
          method: post
