org: justinedelson
app: pd-extract-environment-from-title
service: pd-extract-environment-from-title
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  environment:
    PD_API_KEY: ${param:pagerDutyAPIKey}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  extractTitle:
    handler: bin/extractTitle
    events:
      - httpApi:
          path: /
          method: post
