name = "pd-extract-environment-from-title"
main = "src/index.ts"
compatibility_date = "2022-12-19"

[vars]
MAPPINGS =  "stg=staging,prod=production,lt=load_test"
REGEXES = "in (\\w+) (in|\\[|from),in (\\w+)$,\\[(\\w+)]$"

[env.dev]

[env.dev.vars]
MAPPINGS =  "stg=staging,prod=production,lt=load_test"
REGEXES = "in (\\w+) (in|\\[|from|is),in (\\w+)$,\\[(\\w+)]$"
